export const apiRoutes = {
  profile: '/profile',
  application: '/application',
  applications: '/applications',
  myApplications: '/my-applications',
  qaAll: 'qa-all',
  qa: 'qa',
  comment: 'comment',
  myAppliedApplications: '/my-applied-applications',
  join: '/sign-up',
  login: '/sign-in',
  register: '/register',
  cancel: '/cancel',
  inquiry: '/inquiry',
  getTokenByPassword: '/api/getTokenByPassword',
  getProfile: '/api/getProfile',
  getUserList: '/api/getUserList',
  appointment: '/api/appointment/:id',
  getServices: '/api/getServices',
  getCarDetail: '/api/getCarDetail/:id',
  getInsurance: '/api/getInsurance/:id',
  job: '/api/job/:id?',
  estimates: '/estimates',
  estimatesDetails: '/estimates/details',
  estimatesComplete: '/estimates/complete',
  checkSession: '/hello-world',
  users: '/s/users',
  usersPassword: '/s/users/password',
  userDetail: '/s/users/details',
  requestEmail: '/request/email-validation',
  requestConfirm: '/confirm/email-validation',
  certified: '/s/certified',
  certifications: '/s/certifications',
  diagnosis: {
    dashboard: {
      benchmarkFilter: '/evaluation/self/score/benchmark/details',
      benchmarkData: '/evaluation/self/score/benchmark',
      dashboardPDF: '/evaluation/self/printer/pdf',
      selfScore: '/evaluation/self/score',
    },
    form: {
      list: '/evaluation/self/',
      formDetails: '/evaluation/self/details',
      evaluationResponse: '/evaluation/self/response/details',
      evaluationAllList: '/evaluation/self/response',
    },
    pdf: {
      pdfImg: '/evaluation/printer/',
    },
  },
  trial: {
    trial: '/trial',
    detail: '/trial/evaluation/details',
    preSignedUrl: '/e/signed/trial',
    evaluation: '/trial/evaluation',
    responseDetail: '/trial/evaluation/response/details',
    score: '/trial/evaluation/score',
    benchmarkScore: 'trial/evaluation/score/benchmark',
    pdf: '/trial/printer/pdf',
    createUrl: '/admin/evaluation/trial',
    check: '/trial/hello_world',
  },
  commonCode: {
    emplSales: '/c/codes/empl-sales',
    standards: '/c/codes/standards',
    evaluations: {
      upper: '/c/codes/evaluations/upper',
      by: '/c/codes/evaluations/by',
    },
  },
  clients: {
    s: '/s/clients',
    details: '/s/clients/details',
  },
  attachments: {
    report: '/s/attachments/by-report',
    signed: '/e/signed',
    collabo: '/e/signed/collabo',
  },
  public: {
    base: '/public',
    reports: {
      base: '/public/reports',
      en: '/public/reports/en',
      blockchain: '/public/reports/blockchain',
    },
  },
  report: {
    s: '/s/reports',
    blockchain: '/s/reports/blockchain',
    gen: {
      base: '/s/reports/gen',
      status: '/s/reports/gen/status',
    },
    user: '/s/reports/user',
    description: '/s/reports/gen/description',
    design: '/s/reports/design',
    certified: {
      base: '/s/reports/certified',
      status: '/s/reports/certified/status',
      email: '/s/reports/certified/email',
      estimate: {
        base: '/s/reports/certified/estimate',
        requestAgain: '/s/reports/certified/estimate/request-again',
      },
      statusEng: '/s/reports/certified/status-eng',
    },
    approvers: {
      base: '/s/reports/approvers',
      status: '/s/reports/approvers/status',
      email: '/s/reports/approvers/email',
    },
    status: {
      toApproving: '/s/reports/status/to-approving',
    },
    collaborators: {
      base: '/s/reports/collaborators',
      answers: '/s/reports/collaborators/answers',
      email: '/s/reports/collaborators/email',
      evaluations: '/s/reports/collaborators/evaluations',
      evals: '/s/reports/collaborators/evals',
      status: '/s/reports/collaborators/status',
      evaluationsComment: '/s/reports/collaborators/evaluations/comments',
      toPending: '/s/reports/collaborators/to-pending',
    },
    data: {
      reports: '/data/reports',
      certified: {
        base: '/data/reports/certified',
        denied: '/data/reports/certified/denied',
        arrived: '/data/reports/certified/arrived',
        complete: '/data/reports/certified/complete',
        completeEng: '/data/reports/certified/complete-eng',
        comments: '/data/reports/certified/comments',
        commentsEng: '/data/reports/certified/comments-eng',
        reject: '/data/reports/certified/reject',
        rejectEng: '/data/reports/certified/reject-eng',
        lastAttachments: '/data/reports/certified/last-attachments',
        lastAttachmentsEng: '/data/reports/certified/last-attachments-eng',
        evaluationType: '/data/reports/certified/evaluation-types',
      },
      certifiedEng: '/data/reports/certified-eng',
      evaluationType: '/data/reports/evaluation-types',
      reportsUpload: '/data/reports/upload',
      reportsComplete: '/data/reports/collabo/completed',
      /** 국문리포트 검증없이 검증완료처리 */
      reportsCompleteWithout: '/s/reports/completed/without',
      /** 영문리포트 검증없이 검증완료처리 */
      reportsCompleteEngWithout: '/s/reports/completed/without-eng',
      approver: {
        completed: '/data/reports/approvers/completed',
      },
    },
    relatedEvals: '/data/reports/related-evals',
    evals: {
      base: '/s/reports/evals',
      codes: '/s/reports/evals/codes',
      codesOrder: '/s/reports/evals/codes/order',
      contents: '/s/reports/evals/contents',
      attachments: '/s/reports/evals/contents/attachments',
      remove: '/s/reports/evals/codes/remove',
      related: '/s/reports/evals/related',
      contentsEng: '/s/reports/evals/contents-eng',
      evalsRelatedItem: '/s/reports/evals-related-item',
      evalsRelatedReports: '/s/reports/evals-related-reports',
      evalsRelated: '/s/reports/evals-related',
      rcmd: '/s/reports/evals/rcmd',
    },
    publish: '/s/reports/publish',
    publishEng: '/s/reports/publish-eng',
  },
  material: {
    materialIssues: '/material_issues/',
    issueHistory: '/material_issues/history',
    issues: '/material_issues/issues',
    historyIssueList: '/material_issues/history/issues',
    status: '/material_issues/status',
    stakeHolder: '/material_issues/stakeholder',
    stakeHolderType: '/material_issues/stakeholder/types',
    stakeHolderList: '/material_issues/stakeholder/list',
    stakeHolderPublished: '/material_issues/stakeholder/published',
    materialInvitation: '/material_issues/invitation/',
    materialEmail: '/material_issues/email/',
    materialResendEmail: '/material_issues/stakeholder/email/',
    invitation: '/invitation/material_issues/issues',
    invitationInfo: '/invitation/material_issues/identification',
    progress: '/material_issues/progress',
    identification: '/material_issues/identification',
    stakeHolderProgress: '/material_issues/stakeholder/progress',
    chartData: '/material_issues/answer/data',
  },
};

export const pageRoutes = {
  main: '/',
  auth: '/auth',
  appointment: '/appointment/:id',
};
